[config]

[templates.eww]
input_path = 'colors-eww.scss'
output_path = '~/.config/eww/colors.scss'
scheme = "dark"

[templates.pywalfox]
input_path = 'pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
#post_hook = 'pywalfox update'
scheme = "dark"

[templates.waybar]
input_path = 'colors.css'
output_path = '~/.config/waybar/colors.css'
scheme = "dark"

[templates.foot]
input_path = 'colors-foot.ini'
output_path = '~/.config/foot/colors.ini'
#post_hook = 'pkill -SIGUSR1 foot'
scheme = "dark"

[templates.alacritty]
input_path = 'colors.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.rofi]
input_path = 'rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.rofi_wallpaper]
input_path = 'rofi_wall.rasi'
output_path = '~/.config/cached/current_wall.rasi'

[templates.gtk3]
input_path = 'gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = 'gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.hyprland]
input_path = 'hypr-colrs.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = 'kitty_colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.fuzzel]
input_path = 'fuzzel'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.quickshell_bar]
input_path = 'qs.json'
output_path = '~/.config/quickshell/Colors.js'
#post_hook = 'pkill quickshell && sleep 0.01 && quickshell -p ~/test/entry.qml'

[templates.quickshell_widgets]
input_path = 'qs.json'
output_path = '~/.config/quickshell/bar/widgets/Colors.js'

[templates.quickshell_cols_json]
input_path = 'qs_json.js'
output_path = '~/test/Colors.json'

[templates.quickshell_cols_json_lock]
input_path = 'qs_json.js'
output_path = '~/.config/quickshell/lockscreen/Colors.json'

[templates.quickshell_cols_json_wlogout]
input_path = 'qs_json.js'
output_path = '~/.config/quickshell/menu/Colors.json'

[templates.quickshell_cols_json_idk]
input_path = 'qs_json.js'
output_path = '~/.config/quickshell/Colors.json'

[templates.quickshell_test]
input_path = 'qs.json'
output_path = '~/test/Colors.js'

[templates.quickshell_test_bar]
input_path = 'qs.json'
output_path = '~/test/bar/widgets/Colors.js'

[templates.discord]
input_path = 'discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.ignis]
input_path = 'colors.scss'
output_path = '~/.config/ignis/colors.scss'

[templates.micro]
input_path = 'micro.micro'
output_path = '~/.config/micro/colorschemes/matugen.micro'

[templates.ghostty]
input_path = "ghostty"                  # Path to the template above
output_path = "~/.config/ghostty/themes/Matugen.conf"      # Or matugen-dark/light for variants
post_hook = "pkill -SIGUSR2 ghostty"                       # Reloads Ghostty


